services:
  lucro_admin_database:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/
    environment:
      POSTGRES_USER: otavio
      POSTGRES_DB: lucro_admin_db
      POSTGRES_PASSWORD: otavio1302
    ports:
      - "5432:5432"

  lucro_admin_app:
    image: lucro_admin
    build: .
    command: ["./entrypoint.sh"]
    ports:
      - "8000:8000"
    depends_on:
      - lucro_admin_database
    environment:
      DATABASE_URL: postgresql+psycopg://otavio:otavio1302@lucro_admin_database:5432/lucro_admin_db

volumes:
  pgdata: