import logging
import xml.etree.ElementTree as ET
from datetime import datetime
from decimal import Decimal, InvalidOperation

from lucro_admin.core.entities_produtos import ConfigSku
from lucro_admin.core.imposto.entities_imposto import (
    ErrorParse,
    ProductWithTax,
    SalesTaxes,
    TaxReturn,
)
from lucro_admin.core.imposto.regras_fiscais import uf_without_fcp
from lucro_admin.infra.repositorio_produtos import Produtos

#logger = logging.getLogger('lucroadmin.services.parseXML')


class ParseXML:

    def __init__(self):
        self.namespace: str = '{http://www.portalfiscal.inf.br/nfe}'

    def parse_xml(
        self, xml, id_bling, situacao
    ) -> TaxReturn | ErrorParse:
        """
        parse_xml -> Extraction of taxes by XML tags

        :param self: Object
        :param xml: XML text
        :param id_bling: Unique ID generated by Bling per sale
        :param situacao: Status of the order within Bling (e.g., Fulfilled)
        :return: Taxes broken down by product and total taxes for the sale
        :rtype: ProdutoComImposto | ErrorParse
        """
        difal = fcp = 0

        parse_xml = ET.fromstring(xml)
        products = Produtos()
        '''logger.info(
            'Lucro Admin Parse XML| Starting XML data extraction'
        )'''

        Nfe = parse_xml.find(f'{self.namespace}NFe')

        infNFe = Nfe.find(f'{self.namespace}infNFe')
        if infNFe is None:
            return ErrorParse(tag='infNFe', error='Tag Not Found')

        dest = infNFe.find(f'{self.namespace}dest')
        if dest is None:
            return ErrorParse(tag='dest', error='Tag Not Found')

        ender_dest = dest.find(f'{self.namespace}enderDest')
        if ender_dest is None:
            return ErrorParse(tag='enderDest', error='Tag Not Found')

        uf_recipient = ender_dest.find(f'{self.namespace}UF')
        if uf_recipient is None:
            return ErrorParse(tag='UF', error='Tag Not Found')

        else:
            uf_recipient = ender_dest.find(f'{self.namespace}UF').text
        without_fcp = uf_without_fcp(uf=uf_recipient)

        dets = infNFe.findall(f'{self.namespace}det')

        if dets is None:
            return ErrorParse(tag='det', error='Tag Not Found')

        produtos_com_imposto = []

        for det in dets:
            prod = det.find(f'{self.namespace}prod')
            if prod is not None:
                product_info = self.parse_det_product(
                    det_prod=prod
                )
            else:
                return ErrorParse(tag='prod', error='Tag Not Found')
            tax = det.find(f'{self.namespace}imposto')

            if tax is None:
                return ErrorParse(tag='imposto', error='Tag Not Found')
            else:
                # ICMS Tax
                icms0 = tax.find(f'{self.namespace}ICMS')
                if icms0 is None:
                    return ErrorParse(tag='ICMS', error='Tag não encontrada')
                icms = self.parse_det_tax_icms(det_tax_icms=icms0)

                # PIS Tax
                pis0 = tax.find(f'{self.namespace}PIS')
                if pis0 is None:
                    return ErrorParse(tag='PIS', error='Tag Not Found')
                pis = self.parse_det_tax_pis(det_tax_pis=pis0)

                # COFINS Tax
                cofins0 = tax.find(f'{self.namespace}COFINS')
                if cofins0 is None:
                    return ErrorParse(tag='COFINS', error='Tag Not Found')
                cofins = self.parse_det_tax_cofins(det_tax_cofins=cofins0)

                # If it's an interstate transaction, we have the DIFAL
                if uf_recipient != 'SP':
                    icms_dest = tax.find(f'{self.namespace}ICMSUFDest')
                    if icms_dest is None:
                        return ErrorParse(
                        tag='ICMS_dest', error='Tag Not Found'
                    )
                    difal = self.parse_det_tax_difal(det_tax_difal=icms_dest)

                    if not without_fcp:
                        fcp = self.parse_det_tax_fcp(
                            det_tax_fcp=icms_dest,
                            product_value=product_info['product_value']
                        )

            total_tax = (
                icms + pis + cofins + difal + fcp
            )

            cost_price = products.consulta_custo(SKU=product_info['product'])
            cost_price *= product_info['quantity']
            imposto_produto = ProductWithTax(
                id_bling=id_bling,
                order_status=situacao,
                sku=product_info['product'],
                quantity=product_info['quantity'],
                cost_price=cost_price,
                value=product_info['product_value'],
                icms=icms,
                pis=pis,
                cofins=cofins,
                difal=difal,
                fcp=fcp,
                total=total_tax,
            )
            produtos_com_imposto.append(imposto_produto)

        imposto_venda = SalesTaxes.sum_taxes(
            products_tax=produtos_com_imposto, id_bling=id_bling
        )
        '''logger.info(
            'Lucro Admin Parse XML | Product with itemized taxes -> %s',
            produtos_com_imposto,
        )'''
        return TaxReturn(
            product_tax=produtos_com_imposto, sale_tax=imposto_venda
        )

    def parse_det_product(self, det_prod):
        product_invoice = det_prod.find(f'{self.namespace}cProd')
        if product_invoice is None:
            return ErrorParse(tag='cProd', error='Tag Not Found')
        else:
            product_invoice = det_prod.find(f'{self.namespace}cProd').text
            sku = ConfigSku.configsku(product_invoice)
        vProd = det_prod.find(f'{self.namespace}vProd')
        if vProd is None:
            return ErrorParse(tag='vProd', error='Tag Not Found')
        else:
            vProd = det_prod.find(f'{self.namespace}vProd').text
        qCom = det_prod.find(f'{self.namespace}qCom')
        if qCom is None:
            return ErrorParse(tag='qCom', error='Tag Not Found')
        else:
            qCom = det_prod.find(f'{self.namespace}qCom').text
        qCom_n = self.parse_int_from_xml_quantity(qCom)
        vProd_n = float(vProd)

        return {
            'product': sku,
            'product_value': vProd_n,
            'quantity': qCom_n
        }

    def parse_det_tax_icms(self, det_tax_icms):
        ICMS00 = det_tax_icms.find(f'{self.namespace}ICMS00')

        if ICMS00 is None:
            return ErrorParse(tag='ICMS', error='Tag Not Found')
        else:
            vICMS = ICMS00.find(f'{self.namespace}vICMS')

            if vICMS is None:
                return ErrorParse(
                    tag='vICMS', error='Tag Not Found'
                )
            else:
                vICMS = ICMS00.find(f'{self.namespace}vICMS').text
                vICMS_n = float(vICMS)

        return vICMS_n

    def parse_det_tax_pis(self, det_tax_pis):
        PISAliq = det_tax_pis.find(f'{self.namespace}PISAliq')
        if PISAliq is None:
            return ErrorParse(tag='PISAliq', error='Tag Not Found')

        vPIS = PISAliq.find(f'{self.namespace}vPIS')

        if vPIS is None:
            return ErrorParse(tag='vPIS', error='Tag Not Found')
        else:
            vPIS = PISAliq.find(f'{self.namespace}vPIS').text
            vPIS_n = float(vPIS)

        return vPIS_n

    def parse_det_tax_cofins(self, det_tax_cofins):
        COFINSAliq = det_tax_cofins.find(f'{self.namespace}COFINSAliq')
        if COFINSAliq is None:
            return ErrorParse(tag='COFINSAliq', error='Tag Not Found')
        vCOFINS = COFINSAliq.find(f'{self.namespace}vCOFINS')

        if vCOFINS is None:
            return ErrorParse(tag='vCOFINS', error='Tag Not Found')
        else:
            vCOFINS = COFINSAliq.find(f'{self.namespace}vCOFINS').text
            vCOFINS_n = float(vCOFINS)

        return vCOFINS_n

    def parse_det_tax_difal(self, det_tax_difal):
        vICMS_dest = det_tax_difal.find(f'{self.namespace}vICMSUFDest')
        if vICMS_dest is None:
            return ErrorParse(
                tag='vICMS_dest', error='Tag Not Found'
            )
        else:
            vICMS_dest = det_tax_difal.find(
                f'{self.namespace}vICMSUFDest'
            ).text
            vICMS_dest_n = float(vICMS_dest)

        return vICMS_dest_n

    def parse_det_tax_fcp(self, det_tax_fcp, product_value):
        vFCP = det_tax_fcp.find(f'{self.namespace}vFCPUFDest')
        if vFCP is None:
            return ErrorParse(
                tag='vFCPUFDest', error='Tag Not Found'
            )

        else:
            vFCP = det_tax_fcp.find(f'{self.namespace}vFCPUFDest').text
            vFCP_n = float(vFCP)

        if vFCP_n == 0:
            vFCP_n = product_value * (2 / 100)

        return vFCP_n

    def parse_decimal(self, text: str | None) -> Decimal:
        """
        Safely converts a numeric string to Decimal. Accepts '1', '1.0000',
        and also '1,0000' (replaces comma with a dot).
        """
        if text is None:
            raise ValueError('text None')

        s = text.strip()
        if not s:
            raise ValueError('text vazio')

        s = s.replace(',', '.')

        try:
            return Decimal(s)
        except InvalidOperation as e:
            raise ValueError(f'número inválido: {text!r}') from e

    def parse_int_from_xml_quantity(self, text: str | None) -> int:
        """
        Rule: qCom must be a whole number (integer).
        Accepts '1' and '1.0000' as 1.
        Rejects '1.5' (because that would be fractional).
        """
        q = self.parse_decimal(text)

        # to_integral_value() retorna o Decimal arredondado para inteiro
        # Só aceitamos se não houver parte fracionária:
        if q != q.to_integral_value():
            raise ValueError(f'quantidade fracionada não permitida: {q}')

        return int(q)
