"""Add tables item_pedido, item_pedido_impostos,marketplaces, notas_fiscais, pedidos, produtos, situacao_pedidos_bling, usuarios

Revision ID: 1bf36c18a0da
Revises: 
Create Date: 2026-06-15 14:53:24.527089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bf36c18a0da'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('situacoes_pedidos_bling',
    sa.Column('id_situacao', sa.Integer(), nullable=False),
    sa.Column('id_situacao_bling', sa.Integer(), nullable=False),
    sa.Column('nome_situacao', sa.String(), nullable=False),
    sa.Column('cor_situacao', sa.String(), nullable=False),
    sa.Column('status', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id_situacao', name=op.f('pk_situacoes_pedidos_bling')),
    sa.UniqueConstraint('id_situacao_bling', name=op.f('uq_situacoes_pedidos_bling_id_situacao_bling'))
    )
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nome_usuario', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha_hash', sa.String(), nullable=False),
    sa.Column('status_usuario', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id_usuario', name=op.f('pk_usuarios')),
    sa.UniqueConstraint('email', name=op.f('uq_usuarios_email')),
    sa.UniqueConstraint('nome_usuario', name=op.f('uq_usuarios_nome_usuario'))
    )
    op.create_table('marketplaces',
    sa.Column('id_marketplace', sa.Integer(), nullable=False),
    sa.Column('nome_marketplace', sa.String(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_user_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_user_id'], ['usuarios.id_usuario'], name=op.f('fk_marketplaces_created_user_id_usuarios')),
    sa.ForeignKeyConstraint(['updated_user_id'], ['usuarios.id_usuario'], name=op.f('fk_marketplaces_updated_user_id_usuarios')),
    sa.PrimaryKeyConstraint('id_marketplace', name=op.f('pk_marketplaces')),
    sa.UniqueConstraint('nome_marketplace', name=op.f('uq_marketplaces_nome_marketplace'))
    )
    op.create_table('produtos',
    sa.Column('id_produto', sa.Integer(), nullable=False),
    sa.Column('id_produto_bling', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(), nullable=True),
    sa.Column('descricao_produto', sa.String(), nullable=False),
    sa.Column('fornecedor', sa.String(), nullable=False),
    sa.Column('preco_custo', sa.Numeric(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_user_id'], ['usuarios.id_usuario'], name=op.f('fk_produtos_created_user_id_usuarios')),
    sa.ForeignKeyConstraint(['updated_user_id'], ['usuarios.id_usuario'], name=op.f('fk_produtos_updated_user_id_usuarios')),
    sa.PrimaryKeyConstraint('id_produto', name=op.f('pk_produtos')),
    sa.UniqueConstraint('id_produto_bling', name=op.f('uq_produtos_id_produto_bling')),
    sa.UniqueConstraint('sku', name=op.f('uq_produtos_sku'))
    )
    op.create_table('pedidos',
    sa.Column('id_pedido', sa.Integer(), nullable=False),
    sa.Column('id_bling', sa.Integer(), nullable=False),
    sa.Column('num_bling', sa.Integer(), nullable=False),
    sa.Column('id_situacao', sa.Integer(), nullable=False),
    sa.Column('id_nf_bling', sa.Integer(), nullable=True),
    sa.Column('id_marketplace', sa.Integer(), nullable=False),
    sa.Column('id_pedido_marketplace', sa.Integer(), nullable=True),
    sa.Column('data_venda', sa.DateTime(), nullable=False),
    sa.Column('valor_pedido', sa.Numeric(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_user_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_user_id'], ['usuarios.id_usuario'], name=op.f('fk_pedidos_created_user_id_usuarios')),
    sa.ForeignKeyConstraint(['id_marketplace'], ['marketplaces.id_marketplace'], name=op.f('fk_pedidos_id_marketplace_marketplaces')),
    sa.ForeignKeyConstraint(['id_situacao'], ['situacoes_pedidos_bling.id_situacao'], name=op.f('fk_pedidos_id_situacao_situacoes_pedidos_bling')),
    sa.ForeignKeyConstraint(['updated_user_id'], ['usuarios.id_usuario'], name=op.f('fk_pedidos_updated_user_id_usuarios')),
    sa.PrimaryKeyConstraint('id_pedido', name=op.f('pk_pedidos')),
    sa.UniqueConstraint('id_bling', name=op.f('uq_pedidos_id_bling')),
    sa.UniqueConstraint('num_bling', name=op.f('uq_pedidos_num_bling'))
    )
    op.create_table('item_pedido',
    sa.Column('id_item_pedido', sa.Integer(), nullable=False),
    sa.Column('id_pedido', sa.Integer(), nullable=False),
    sa.Column('id_situacao', sa.Integer(), nullable=False),
    sa.Column('id_produto', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco_custo', sa.Numeric(), nullable=False),
    sa.Column('preco_venda_unitario', sa.Numeric(), nullable=False),
    sa.Column('frete_item', sa.Numeric(), nullable=False),
    sa.Column('comissao_item', sa.Numeric(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_user_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_user_id'], ['usuarios.id_usuario'], name=op.f('fk_item_pedido_created_user_id_usuarios')),
    sa.ForeignKeyConstraint(['id_pedido'], ['pedidos.id_pedido'], name=op.f('fk_item_pedido_id_pedido_pedidos')),
    sa.ForeignKeyConstraint(['id_produto'], ['produtos.id_produto'], name=op.f('fk_item_pedido_id_produto_produtos')),
    sa.ForeignKeyConstraint(['id_situacao'], ['situacoes_pedidos_bling.id_situacao'], name=op.f('fk_item_pedido_id_situacao_situacoes_pedidos_bling')),
    sa.ForeignKeyConstraint(['updated_user_id'], ['usuarios.id_usuario'], name=op.f('fk_item_pedido_updated_user_id_usuarios')),
    sa.PrimaryKeyConstraint('id_item_pedido', name=op.f('pk_item_pedido'))
    )
    op.create_table('notas_fiscais',
    sa.Column('id_nf', sa.Integer(), nullable=False),
    sa.Column('id_pedido', sa.Integer(), nullable=False),
    sa.Column('created_user_id', sa.Integer(), nullable=False),
    sa.Column('updated_user_id', sa.Integer(), nullable=False),
    sa.Column('url_xml', sa.String(), nullable=True),
    sa.Column('serie', sa.Integer(), nullable=True),
    sa.Column('chave_acesso', sa.String(), nullable=True),
    sa.Column('data_emissao', sa.Date(), nullable=True),
    sa.Column('valor_nf', sa.Numeric(), nullable=True),
    sa.Column('id_nf_bling', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_user_id'], ['usuarios.id_usuario'], name=op.f('fk_notas_fiscais_created_user_id_usuarios')),
    sa.ForeignKeyConstraint(['id_pedido'], ['pedidos.id_pedido'], name=op.f('fk_notas_fiscais_id_pedido_pedidos')),
    sa.ForeignKeyConstraint(['updated_user_id'], ['usuarios.id_usuario'], name=op.f('fk_notas_fiscais_updated_user_id_usuarios')),
    sa.PrimaryKeyConstraint('id_nf', name=op.f('pk_notas_fiscais')),
    sa.UniqueConstraint('chave_acesso', name=op.f('uq_notas_fiscais_chave_acesso')),
    sa.UniqueConstraint('id_pedido', name=op.f('uq_notas_fiscais_id_pedido'))
    )
    op.create_table('itens_pedido_imposto',
    sa.Column('id_item_pedido_imposto', sa.Integer(), nullable=False),
    sa.Column('id_item_pedido', sa.Integer(), nullable=False),
    sa.Column('tipo_imposto', sa.String(), nullable=False),
    sa.Column('valor_imposto', sa.Numeric(), nullable=False),
    sa.Column('origem_calculo', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_user_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_user_id'], ['usuarios.id_usuario'], name=op.f('fk_itens_pedido_imposto_created_user_id_usuarios')),
    sa.ForeignKeyConstraint(['id_item_pedido'], ['item_pedido.id_item_pedido'], name=op.f('fk_itens_pedido_imposto_id_item_pedido_item_pedido')),
    sa.ForeignKeyConstraint(['updated_user_id'], ['usuarios.id_usuario'], name=op.f('fk_itens_pedido_imposto_updated_user_id_usuarios')),
    sa.PrimaryKeyConstraint('id_item_pedido_imposto', name=op.f('pk_itens_pedido_imposto'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itens_pedido_imposto')
    op.drop_table('notas_fiscais')
    op.drop_table('item_pedido')
    op.drop_table('pedidos')
    op.drop_table('produtos')
    op.drop_table('marketplaces')
    op.drop_table('usuarios')
    op.drop_table('situacoes_pedidos_bling')
    # ### end Alembic commands ###
