"""Mudando o tipo do atributo data_venda do pedido de datetime para date

Revision ID: 1c20a32e3bd5
Revises: 1bf36c18a0da
Create Date: 2026-06-16 09:47:11.316012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c20a32e3bd5'
down_revision: Union[str, Sequence[str], None] = '1bf36c18a0da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pedidos") as batch_op:
        batch_op.alter_column(
            "data_venda",
            existing_type=sa.DateTime(),
            type_=sa.Date(),
            existing_nullable=False,
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pedidos") as batch_op:
        batch_op.alter_column(
            "data_venda",
            existing_type=sa.Date(),
            type_=sa.DateTime(),
            existing_nullable=False,
        )
    # ### end Alembic commands ###
