"""Unique SKU in products

Revision ID: 2be7301cfa1e
Revises: 2a685b2f06a6
Create Date: 2026-08-12 15:18:33.530365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2be7301cfa1e'
down_revision: Union[str, Sequence[str], None] = '2a685b2f06a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'sku',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(op.f('uq_products_sku'), 'products', ['sku'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_products_sku'), 'products', type_='unique')
    op.alter_column('products', 'sku',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
