"""Criando a tabela de usuários

Revision ID: 378550726401
Revises: 
Create Date: 2026-06-10 19:08:57.711034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '378550726401'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('situacoes_pedidos_bling',
    sa.Column('id_situacao', sa.Integer(), nullable=False),
    sa.Column('id_situacao_bling', sa.Integer(), nullable=False),
    sa.Column('nome_situacao', sa.String(), nullable=False),
    sa.Column('cor_situacao', sa.String(), nullable=False),
    sa.Column('status', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id_situacao'),
    sa.UniqueConstraint('id_situacao_bling')
    )
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nome_usuario', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha_hash', sa.String(), nullable=False),
    sa.Column('status_usuario', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nome_usuario')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios')
    op.drop_table('situacoes_pedidos_bling')
    # ### end Alembic commands ###
