"""integration foreign key in orders

Revision ID: 4640c8583101
Revises: 6fae87309706
Create Date: 2026-08-14 18:55:32.598577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4640c8583101'
down_revision: Union[str, Sequence[str], None] = '6fae87309706'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('integration_order_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('integration_invoice_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_orders_integration_order_id_integrations'), 'orders', 'integrations', ['integration_order_id'], ['integration_id'])
    op.create_foreign_key(op.f('fk_orders_integration_invoice_id_integrations'), 'orders', 'integrations', ['integration_invoice_id'], ['integration_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_orders_integration_invoice_id_integrations'), 'orders', type_='foreignkey')
    op.drop_constraint(op.f('fk_orders_integration_order_id_integrations'), 'orders', type_='foreignkey')
    op.drop_column('orders', 'integration_invoice_id')
    op.drop_column('orders', 'integration_order_id')
    # ### end Alembic commands ###
