"""Insert slug in marketplaces

Revision ID: 4f48c659f80a
Revises: 916d407ca3d3
Create Date: 2026-08-31 14:51:09.499724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f48c659f80a'
down_revision: Union[str, Sequence[str], None] = '916d407ca3d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marketplaces', sa.Column('slug', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('marketplaces', 'slug')
    # ### end Alembic commands ###
