"""Alter column unique false

Revision ID: 5f64ae3498c9
Revises: 49558cad2e0e
Create Date: 2026-08-08 17:16:34.775858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f64ae3498c9'
down_revision: Union[str, Sequence[str], None] = '49558cad2e0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_products_sku'), 'products', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_products_sku'), 'products', ['sku'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
