"""Unique constraint external_id logistics

Revision ID: 6afda44314f2
Revises: c22cedfb55f2
Create Date: 2026-08-11 15:51:21.908189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6afda44314f2'
down_revision: Union[str, Sequence[str], None] = 'c22cedfb55f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('services_logistics', 'service_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('uq_services_logistics_service_name'), 'services_logistics', type_='unique')
    op.create_unique_constraint(op.f('uq_services_logistics_external_service_id'), 'services_logistics', ['external_service_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_services_logistics_external_service_id'), 'services_logistics', type_='unique')
    op.create_unique_constraint(op.f('uq_services_logistics_service_name'), 'services_logistics', ['service_name'], postgresql_nulls_not_distinct=False)
    op.alter_column('services_logistics', 'service_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
