"""Delete table logistics and delete foreing key in orders

Revision ID: 6d08b2f6c6f4
Revises: 6afda44314f2
Create Date: 2026-08-11 21:24:59.868761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6d08b2f6c6f4'
down_revision: Union[str, Sequence[str], None] = '6afda44314f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('transport', sa.String(), nullable=True))
    op.drop_constraint(op.f('fk_orders_service_logistics_id_services_logistics'), 'orders', type_='foreignkey')
    op.drop_column('orders', 'service_logistics_id')
    op.drop_table('services_logistics')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('service_logistics_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_orders_service_logistics_id_services_logistics'), 'orders', 'services_logistics', ['service_logistics_id'], ['service_id'])
    op.drop_column('orders', 'transport')
    op.create_table('services_logistics',
    sa.Column('service_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('external_service_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('service_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('logistics_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_user_id'], ['users.user_id'], name=op.f('fk_services_logistics_created_user_id_users')),
    sa.ForeignKeyConstraint(['updated_user_id'], ['users.user_id'], name=op.f('fk_services_logistics_updated_user_id_users')),
    sa.PrimaryKeyConstraint('service_id', name=op.f('pk_services_logistics')),
    sa.UniqueConstraint('external_service_id', name=op.f('uq_services_logistics_external_service_id'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
