"""Integration table

Revision ID: 6fae87309706
Revises: 7f81a4a80556
Create Date: 2026-08-14 18:41:18.705212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fae87309706'
down_revision: Union[str, Sequence[str], None] = '7f81a4a80556'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integrations',
    sa.Column('integration_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('integration_id', name=op.f('pk_integrations')),
    sa.UniqueConstraint('name', name=op.f('uq_integrations_name'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('integrations')
    # ### end Alembic commands ###
