"""Create Table Fulfillment_Product

Revision ID: 7f81a4a80556
Revises: 2be7301cfa1e
Create Date: 2026-08-13 11:48:46.544030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f81a4a80556'
down_revision: Union[str, Sequence[str], None] = '2be7301cfa1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fulfillment_product',
    sa.Column('product_full_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('marketplace_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('fulfillment_sku', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_user_id'], ['users.user_id'], name=op.f('fk_fulfillment_product_created_user_id_users')),
    sa.ForeignKeyConstraint(['marketplace_id'], ['marketplaces.marketplace_id'], name=op.f('fk_fulfillment_product_marketplace_id_marketplaces')),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], name=op.f('fk_fulfillment_product_product_id_products')),
    sa.ForeignKeyConstraint(['updated_user_id'], ['users.user_id'], name=op.f('fk_fulfillment_product_updated_user_id_users')),
    sa.PrimaryKeyConstraint('product_full_id', name=op.f('pk_fulfillment_product')),
    sa.UniqueConstraint('fulfillment_sku', name=op.f('uq_fulfillment_product_fulfillment_sku'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fulfillment_product')
    # ### end Alembic commands ###
