"""Delete atributes external_invoice_id and external_integration_invoice_id

Revision ID: 916d407ca3d3
Revises: 871a743fa953
Create Date: 2026-08-25 16:31:42.885701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '916d407ca3d3'
down_revision: Union[str, Sequence[str], None] = '871a743fa953'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_tax_invoice_external_invoice_integration_id_integrations'), 'tax_invoice', type_='foreignkey')
    op.drop_column('tax_invoice', 'external_tax_invoice_id')
    op.drop_column('tax_invoice', 'external_invoice_integration_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tax_invoice', sa.Column('external_invoice_integration_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('tax_invoice', sa.Column('external_tax_invoice_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_tax_invoice_external_invoice_integration_id_integrations'), 'tax_invoice', 'integrations', ['external_invoice_integration_id'], ['integration_id'])
    # ### end Alembic commands ###
