"""First Lucro Admin data base

Revision ID: bd8a871946c5
Revises: 
Create Date: 2026-07-30 10:15:09.454339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd8a871946c5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bling_orders_situation',
    sa.Column('situation_id', sa.Integer(), nullable=False),
    sa.Column('situation_bling_id', sa.Integer(), nullable=False),
    sa.Column('situation_name', sa.String(), nullable=False),
    sa.Column('situation_color', sa.String(), nullable=False),
    sa.Column('status', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('situation_id', name=op.f('pk_bling_orders_situation')),
    sa.UniqueConstraint('situation_bling_id', name=op.f('uq_bling_orders_situation_situation_bling_id'))
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('user_status', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('user_name', name=op.f('uq_users_user_name'))
    )
    op.create_table('marketplaces',
    sa.Column('marketplace_id', sa.Integer(), nullable=False),
    sa.Column('marketplace_external_id', sa.Integer(), nullable=False),
    sa.Column('external_type', sa.String(), nullable=True),
    sa.Column('marketplace_name', sa.String(), nullable=False),
    sa.Column('status', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_user_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_user_id'], ['users.user_id'], name=op.f('fk_marketplaces_created_user_id_users')),
    sa.ForeignKeyConstraint(['updated_user_id'], ['users.user_id'], name=op.f('fk_marketplaces_updated_user_id_users')),
    sa.PrimaryKeyConstraint('marketplace_id', name=op.f('pk_marketplaces')),
    sa.UniqueConstraint('marketplace_external_id', name=op.f('uq_marketplaces_marketplace_external_id'))
    )
    op.create_table('products',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_bling_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(), nullable=True),
    sa.Column('product_description', sa.String(), nullable=False),
    sa.Column('supplier', sa.String(), nullable=False),
    sa.Column('cost_price', sa.Numeric(), nullable=False),
    sa.Column('origin', sa.Integer(), nullable=False),
    sa.Column('ncm', sa.String(), nullable=False),
    sa.Column('cest', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_user_id'], ['users.user_id'], name=op.f('fk_products_created_user_id_users')),
    sa.ForeignKeyConstraint(['updated_user_id'], ['users.user_id'], name=op.f('fk_products_updated_user_id_users')),
    sa.PrimaryKeyConstraint('product_id', name=op.f('pk_products')),
    sa.UniqueConstraint('product_bling_id', name=op.f('uq_products_product_bling_id')),
    sa.UniqueConstraint('sku', name=op.f('uq_products_sku'))
    )
    op.create_table('orders',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('bling_id', sa.Integer(), nullable=False),
    sa.Column('bling_num', sa.Integer(), nullable=False),
    sa.Column('situation_id', sa.Integer(), nullable=False),
    sa.Column('tax_invoice_bling_id', sa.Integer(), nullable=True),
    sa.Column('marketplace_id', sa.Integer(), nullable=True),
    sa.Column('marketplace_order_id', sa.Integer(), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('value_order', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_user_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_user_id'], ['users.user_id'], name=op.f('fk_orders_created_user_id_users')),
    sa.ForeignKeyConstraint(['marketplace_id'], ['marketplaces.marketplace_id'], name=op.f('fk_orders_marketplace_id_marketplaces')),
    sa.ForeignKeyConstraint(['situation_id'], ['bling_orders_situation.situation_id'], name=op.f('fk_orders_situation_id_bling_orders_situation')),
    sa.ForeignKeyConstraint(['updated_user_id'], ['users.user_id'], name=op.f('fk_orders_updated_user_id_users')),
    sa.PrimaryKeyConstraint('order_id', name=op.f('pk_orders')),
    sa.UniqueConstraint('bling_id', name=op.f('uq_orders_bling_id')),
    sa.UniqueConstraint('bling_num', name=op.f('uq_orders_bling_num'))
    )
    op.create_table('order_item',
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('situation_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('cost_price', sa.Numeric(), nullable=False),
    sa.Column('unit_selling_price', sa.Numeric(), nullable=False),
    sa.Column('item_shipping', sa.Numeric(), nullable=True),
    sa.Column('item_commission', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_user_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_user_id'], ['users.user_id'], name=op.f('fk_order_item_created_user_id_users')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], name=op.f('fk_order_item_order_id_orders')),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], name=op.f('fk_order_item_product_id_products')),
    sa.ForeignKeyConstraint(['situation_id'], ['bling_orders_situation.situation_id'], name=op.f('fk_order_item_situation_id_bling_orders_situation')),
    sa.ForeignKeyConstraint(['updated_user_id'], ['users.user_id'], name=op.f('fk_order_item_updated_user_id_users')),
    sa.PrimaryKeyConstraint('order_item_id', name=op.f('pk_order_item'))
    )
    op.create_table('tax_invoice',
    sa.Column('tax_invoice_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('created_user_id', sa.Integer(), nullable=False),
    sa.Column('updated_user_id', sa.Integer(), nullable=False),
    sa.Column('url_xml', sa.String(), nullable=True),
    sa.Column('serie', sa.Integer(), nullable=True),
    sa.Column('key_access', sa.String(), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('tax_invoice_value', sa.Numeric(), nullable=True),
    sa.Column('bling_tax_invoice_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_user_id'], ['users.user_id'], name=op.f('fk_tax_invoice_created_user_id_users')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], name=op.f('fk_tax_invoice_order_id_orders')),
    sa.ForeignKeyConstraint(['updated_user_id'], ['users.user_id'], name=op.f('fk_tax_invoice_updated_user_id_users')),
    sa.PrimaryKeyConstraint('tax_invoice_id', name=op.f('pk_tax_invoice')),
    sa.UniqueConstraint('key_access', name=op.f('uq_tax_invoice_key_access')),
    sa.UniqueConstraint('order_id', name=op.f('uq_tax_invoice_order_id'))
    )
    op.create_table('order_item_tax',
    sa.Column('order_item_tax_id', sa.Integer(), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('tax_type', sa.String(), nullable=False),
    sa.Column('tax_value', sa.Numeric(), nullable=False),
    sa.Column('calculation_source', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_user_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_user_id'], ['users.user_id'], name=op.f('fk_order_item_tax_created_user_id_users')),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_item.order_item_id'], name=op.f('fk_order_item_tax_order_item_id_order_item')),
    sa.ForeignKeyConstraint(['updated_user_id'], ['users.user_id'], name=op.f('fk_order_item_tax_updated_user_id_users')),
    sa.PrimaryKeyConstraint('order_item_tax_id', name=op.f('pk_order_item_tax')),
    sa.UniqueConstraint('order_item_id', 'tax_type', name='uq_item_pedido_imposto_tipo')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_item_tax')
    op.drop_table('tax_invoice')
    op.drop_table('order_item')
    op.drop_table('orders')
    op.drop_table('products')
    op.drop_table('marketplaces')
    op.drop_table('users')
    op.drop_table('bling_orders_situation')
    # ### end Alembic commands ###
