"""Logistics Services Table

Revision ID: c22cedfb55f2
Revises: 5f64ae3498c9
Create Date: 2026-08-11 07:42:50.080388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c22cedfb55f2'
down_revision: Union[str, Sequence[str], None] = '5f64ae3498c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services_logistics',
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('external_service_id', sa.BigInteger(), nullable=False),
    sa.Column('service_name', sa.String(), nullable=False),
    sa.Column('logistics_name', sa.String(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_user_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_user_id'], ['users.user_id'], name=op.f('fk_services_logistics_created_user_id_users')),
    sa.ForeignKeyConstraint(['updated_user_id'], ['users.user_id'], name=op.f('fk_services_logistics_updated_user_id_users')),
    sa.PrimaryKeyConstraint('service_id', name=op.f('pk_services_logistics')),
    sa.UniqueConstraint('service_name', name=op.f('uq_services_logistics_service_name'))
    )
    op.add_column('orders', sa.Column('uf_dest', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('service_logistics_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_orders_service_logistics_id_services_logistics'), 'orders', 'services_logistics', ['service_logistics_id'], ['service_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_orders_service_logistics_id_services_logistics'), 'orders', type_='foreignkey')
    op.drop_column('orders', 'service_logistics_id')
    op.drop_column('orders', 'uf_dest')
    op.drop_table('services_logistics')
    # ### end Alembic commands ###
