"""Insert integration id in tax_order

Revision ID: c6cf4c0cc810
Revises: 4640c8583101
Create Date: 2026-08-18 14:43:45.158880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6cf4c0cc810'
down_revision: Union[str, Sequence[str], None] = '4640c8583101'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tax_invoice',
    sa.Column('tax_invoice_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('url_xml', sa.String(), nullable=True),
    sa.Column('serie', sa.Integer(), nullable=True),
    sa.Column('key_access', sa.String(), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('tax_invoice_value', sa.Numeric(), nullable=True),
    sa.Column('external_tax_invoice_id', sa.Integer(), nullable=True),
    sa.Column('external_invoice_integration_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_user_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_user_id'], ['users.user_id'], name=op.f('fk_tax_invoice_created_user_id_users')),
    sa.ForeignKeyConstraint(['external_invoice_integration_id'], ['integrations.integration_id'], name=op.f('fk_tax_invoice_external_invoice_integration_id_integrations')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], name=op.f('fk_tax_invoice_order_id_orders')),
    sa.ForeignKeyConstraint(['updated_user_id'], ['users.user_id'], name=op.f('fk_tax_invoice_updated_user_id_users')),
    sa.PrimaryKeyConstraint('tax_invoice_id', name=op.f('pk_tax_invoice')),
    sa.UniqueConstraint('key_access', name=op.f('uq_tax_invoice_key_access')),
    sa.UniqueConstraint('order_id', name=op.f('uq_tax_invoice_order_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tax_invoice')
    # ### end Alembic commands ###
