"""Inserção de dados tributários dos produtos

Revision ID: f81ed2bc1db1
Revises: 1c20a32e3bd5
Create Date: 2026-07-21 11:50:29.416302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f81ed2bc1db1'
down_revision: Union[str, Sequence[str], None] = '1c20a32e3bd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_item_pedido_imposto_tipo', 'itens_pedido_imposto', ['id_item_pedido', 'tipo_imposto'])
    op.add_column('produtos', sa.Column('origem', sa.Integer(), nullable=False))
    op.add_column('produtos', sa.Column('ncm', sa.String(), nullable=False))
    op.add_column('produtos', sa.Column('cest', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produtos', 'cest')
    op.drop_column('produtos', 'ncm')
    op.drop_column('produtos', 'origem')
    op.drop_constraint('uq_item_pedido_imposto_tipo', 'itens_pedido_imposto', type_='unique')
    # ### end Alembic commands ###
