import logging
from dataclasses import dataclass
from datetime import datetime
from typing import Any, Literal

logger = logging.getLogger('lucroadmin.core.entities')


@dataclass
class BlingSituation:
    """
    BlingSituation -> Standardized formatting for order situations within Bling

    Attributes:
        cod_sit: Situation code
        :type cod_sit: int
        name_sit: Name of the Situation (Ex: Atendido)
        :type name_sit: str
    """

    cod_sit: int
    name_sit: str
    color_sit: str | None = None


@dataclass
class PageResult:
    """
        PageResult -> Standardizing the return of requests for Bling endpoints.

        Attributes:
            status: status of the request return.
            :type status: Literal [ok, rated_limit, error]
            data: Data from the request.
            :type data: Any | None = None
            error: In case there's an error, we put it in this attribute to handle it.
            :type error: Any = None
    """  # noqa: E501

    status: Literal['ok', 'rated_limit', 'error']
    data: Any | None = None
    error: Any = None


@dataclass
class ErrorHTTP:
    """
    ErrorHTTP -> HTTP error standardization, so we can handle the fallback
    after active executions

    Attributes:
        status:We use by default the same status from the PageResult Class (ok, rated_limit, error).
        :type status: Literal ['rated_limit', 'error']
        error: It's the same error already set up in the paginaResultado Class, that is, it's the response body of the request.
        :type error: Any
        method: It's the method used, meaning the executed def that encountered the error.
        :type method: str
        class_name: The class to which the method belongs
        :type class: str
        module: The file where the method is located.
        :type module: str
        endpoint: The API Endpoint where the request was made
        :type endpoint: str
        data: The exact date of sending this request
        :type data: datetime
    """  # noqa: E501

    status: Literal['rated_limit', 'error']
    error: Any
    method: str
    class_name: str
    module: str
    endpoint: str
    data: datetime


@dataclass
class GetPagesResult:
    """
    GetPagesResult -> Result of the get_id_por_pag method

    Attributes:
        sales_id: List with all unique Bling IDs per sale
        :type sales_id: list[int]
        endpointerror: List with specifications of the endpoint where we got an error response. Type ErrorHTTP
        :type endpointerror: list[ErrorHTTP]
        situation: Name of the situation the obtained orders are in (Ex: Cancelado)
        :type situation: str
    """  # noqa: E501

    sales_id: list[int]
    endpointerro: list[ErrorHTTP]
    situation: str


@dataclass
class GetDetailsResult:
    """
    GetDetailsResult -> Result of the get_id_details method

    Attributes:
        orders: List with all fetched orders. Type OrderData
        :type orders: list[OrderData]
        endpointerror: List with specifications of the endpoint where we got an error response. Type HTTPError
        :type endpointerror: list[HTTPError]
        situation: Name of the situation the fetched orders are in (Ex: Cancelado)
        :type situation: str
    """  # noqa: E501

    orders: list[Any]
    endpointerror: list[ErrorHTTP]
    situation: str


@dataclass
class OrderData:
    """
    OrderData -> Formatting and organizing the order data

    Attributes:
        id_bling: Unique sale ID, this ID is generated by Bling
        :type id_bling: int
        num_bling: Unique sale number generated by Bling
        :type num_bling: int
        id_mkt: Sale number generated by the Marketplace
        :type id_mkt: int
        data: Sale date
        :type data: datetime
        nome_store: Name of the store where the sale was made
        :type nome_store: str
        nf_id: Unique invoice ID generated by Bling
        :type nd_id: int
        value_sale: Total sale amount
        :type value_sale: float
        items: Data of all sale items
        :type items: list
        uf_dest: Destination state of the sale
        :type uf_dest: str
    """

    id_bling: int
    num_bling: int
    id_mkt: int
    data: datetime
    name_store: str
    nf_id: int
    value_sale: float
    items: list
    uf_dest: str
    servico_trans: str | Any


@dataclass
class Dados_Pedido_imposto:
    id_bling: int
    num_bling: int
    situacao: str
    id_mkt: int
    data: datetime
    nome_loja: str
    nf_id: int
    valor_pedido: float
    servico_trans: str | Any
    icms: float
    pis: float
    cofins: float
    difal: float
    fcp: float
    total: float
    custo_produto: float


@dataclass
class PedidoCompleto:
    id_bling: int
    num_bling: int
    situacao: str
    id_mkt: int
    data: datetime
    nome_loja: str
    nf_id: int
    valor_pedido: float
    icms: float
    pis: float
    cofins: float
    difal: float
    fcp: float
    total_imposto: float
    custo_produto: float
    comissao: float
    frete: float
    lucro: float


@dataclass
class PedidoseImpostos:
    pedidos: list[Any]
    impostos_produto: list[Any]


@dataclass
class ComissaoFrete:
    id_bling: int
    comissao: float
    frete: float


@dataclass
class IdsPedidoML:
    comissao: float
    pay_id: int
    pack_id: int
    geral: Any


@dataclass
class ShipCommission:
    id: int
    commission: float
    ship_cost: float
    sku: str


@dataclass
class SaleCosts:
    costs: list[ShipCommission]


@dataclass
class ProdutoCompleto:
    id_bling: int
    situacao_pedido: str
    sku: str
    quantidade: int
    preco_custo: float
    valor: float
    icms: float
    pis: float
    cofins: float
    difal: float
    fcp: float
    total_imposto: float
    frete: float
    comissao: float


@dataclass
class PedidoseProdutosCompletos:
    pedidos: list[Any]
    produtos: list[Any]
