import logging

from lucro_admin.core.entities_produtos import ConfigSku
from lucro_admin.core.imposto.entities_imposto import (
    OrderItem,
    ProductWithTax,
    SalesTaxes,
    TaxReturn,
)
from lucro_admin.core.imposto.regras_fiscais import icms_aliq, uf_sem_fcp
from lucro_admin.infra.repositorio_produtos import Produtos

logger = logging.getLogger('lucroadmin.core.taxcalculator')


class TaxCalculator:
    """
    TaxCalculator

        Manually calculates taxes for internal and interstate operations.
        Taxes calculated include ICMS, PIS, COFINS, DIFAL, and FCP
    """

    def __init__(self):
        self.aliq_pis = 1.65 / 100
        self.aliq_cofins = 7.6 / 100

    def tax_calculator(
        self, items, id_bling, sit, uf_dest
    ) -> TaxReturn:
        """
        tax_calculator

        Calculating the taxes of a sale accurately and returning them in an
        organized and formatted way.

        :param self:
        :param items: Order products
        :param id_bling: Unique sale ID, this ID is generated by Bling
        :param status: Order status within Bling
        :param uf_dest: Federal Unit of the sale destination
        :return: Individual return per product as well as totalled for the sale
        :rtype: TaxReturn
        """

        logger.info(
            'Tax Calculator | Starting the tax calculation'
            ' for the order items'
        )

        products = Produtos()
        # Validating FCP and PIS and COFINS rates
        without_fcp = uf_sem_fcp(uf_dest)
        products_with_tax = []

        # Looping to go through all the items in the sale
        for item in items:
            item_order = OrderItem(
                code=item['codigo'],
                quantity=item['quantidade'],
                value=item['valor'],
            )
            # Setting up the SKU because some come with incorrectly
            # formatted SKUs.
            sku = ConfigSku.configsku(item_order.code)
            icms = pis = cofins = difal = fcp = 0.0

            # Validating whether the sale is a local or interstate operation
            if uf_dest == 'SP':
                logger.info(
                    'Tax Calculator | State of origin SP and destination state'
                    ' %s -> Characterizes internal operation',
                    uf_dest,
                )
                icms = item_order.value * (18 / 100)
                pis = (item_order.value - icms) * self.aliq_pis
                cofins = (item_order.value - icms) * self.aliq_cofins
            # If it's interstate, we need to check if the destination state
            # charges the fund to fight poverty or not.
            elif without_fcp:
                logger.info(
                    'Calculadora de Tributos | UF de origem SP e UF destino %s'
                    ' -> Caracteriza operação interestadual, mas a UF não tem'
                    ' cobrança do FCP',
                    uf_dest,
                )
                aliq_dest_total = icms_aliq(uf_dest) / 100
                aliq_orig = 4 / 100
                aliq_dest = aliq_dest_total - aliq_orig
                icms = item_pedido.valor * aliq_orig
                difal = item_pedido.valor * aliq_dest
                pis = (item_pedido.valor - (icms + difal)) * self.aliq_pis
                cofins = (
                    item_pedido.valor - (icms + difal)
                ) * self.aliq_cofins

            else:
                logger.info(
                    'Calculadora de Tributos | UF de origem SP e UF destino %s'
                    ' -> Caracteriza operação interestadual, mas a UF tem'
                    ' cobrança do FCP',
                    uf_dest,
                )
                aliq_dest_total = icms_aliq(uf_dest) / 100
                aliq_orig = 4 / 100
                aliq_fcp = 2 / 100
                aliq_dest = aliq_dest_total - aliq_orig
                icms = item_pedido.valor * aliq_orig
                difal = item_pedido.valor * aliq_dest
                pis = (item_pedido.valor - (icms + difal)) * self.aliq_pis
                cofins = (
                    item_pedido.valor - (icms + difal)
                ) * self.aliq_cofins
                fcp = item_pedido.valor * aliq_fcp

            total = icms + pis + cofins + difal + fcp

            preco_custo = produtos.consulta_custo(SKU=sku)
            preco_custo *= item_pedido.quantidade
            # Formatando os impostos do produto para um dataclass
            imposto_produto = ProdutoComImposto(
                id_bling=id_bling,
                situacao_pedido=sit,
                sku=sku,
                quantidade=item_pedido.quantidade,
                preco_custo=preco_custo,
                valor=item_pedido.valor,
                icms=icms,
                pis=pis,
                cofins=cofins,
                difal=difal,
                fcp=fcp,
                total=total,
            )
            logger.info(
                'Calculadora de Tributos | Tributo do produto calculado ->'
                ' %s\nMateus 22:21',
                imposto_produto,
            )
            produtos_com_imposto.append(imposto_produto)

        # Somando todos os impostos dos itens para totalizarmos os impostos
        # da venda.
        impostos_venda = ImpostosDaVenda.soma_impostos(
            produtos_com_imposto, id_bling=id_bling
        )
        logger.info(
            'Calculadora de Tributos | Tributo da venda calculado ->'
            ' %s\nMateus 22:21',
            impostos_venda,
        )
        return RetornoImpostos(
            produto_imposto=produtos_com_imposto, venda_imposto=impostos_venda
        )
