from dataclasses import dataclass


@dataclass
class ProductWithTax:
    """
    ProductWithTax

    Attributes:
        id_bling: Unique sale ID generated by Bling
        situacao_pedido: Order status within Bling
        sku: Product SKU
        quantidade: Quantity of the item sold
        value: Product sale value
        icms: Amount paid in ICMS
        pis: Amount paid in PIS
        cofins: Amount paid in COFINS
        difal: Amount paid in DIFAL
        fcp: Amount paid in FCP
        total: Total amount of tax paid on the product sale
    """

    id_bling: int
    order_status: str
    sku: str
    quantity: int
    cost_price: float
    value: float
    icms: float
    pis: float
    cofins: float
    difal: float
    fcp: float
    total: float


@dataclass
class SalesTaxes:
    """
    SalesTaxes

    Attributes:
        id_bling: Unique ID generated by Bling
        icms: ICMS amount paid
        pis: PIS amount paid
        cofins: COFINS amount paid
        difal: DIFAL amount paid
        total: Total tax amount paid on the sale
    """

    id_bling: int
    icms: float
    pis: float
    cofins: float
    difal: float
    fcp: float
    total: float
    cost: float

    @classmethod
    def sum_taxes(cls, products_tax, id_bling) -> 'SalesTaxes':
        """
        Sum of product taxes to generate total taxes for the sale

        :param cls:
        :param produtos_imposto: List of products with individual taxes
        :param id_bling: Unique ID generated by Bling
        :return: Formatted return for sale taxes
        :rtype: SaleTaxes
        """
        return cls(
            id_bling=id_bling,
            icms=sum(p.icms for p in products_tax),
            pis=sum(p.pis for p in products_tax),
            cofins=sum(p.cofins for p in products_tax),
            difal=sum(p.difal for p in products_tax),
            fcp=sum(p.fcp for p in products_tax),
            total=sum(p.total for p in products_tax),
            cost=sum(p.cost_price for p in products_tax),
        )


@dataclass
class TaxReturn:
    """
    TaxReturn

    Attributes:
        product_tax: It's a list with products itemized with taxes paid.
        sale_tax: These are the total taxes of the sale.

    """

    product_tax: list[ProductWithTax]
    sale_tax: SalesTaxes


@dataclass
class OrderItem:
    """
    OrderItem

    Attributes:
        code: Product SKU
        quantity: Quantity sold
        value: Sale value
    """

    code: str
    quantity: int
    value: float


@dataclass
class ErrorParse:
    """
    ErrorParse

    Attributes:
        tag: XML tag that was not found
        error: Type of error.

    """

    tag: str
    error: str
