import logging

from lucro_admin.core.entities_produtos import ConfigSku
from lucro_admin.core.imposto.entities_imposto import (
    OrderItem,
    ProductWithTax,
    SalesTaxes,
    TaxReturn,
)
from lucro_admin.core.imposto.regras_fiscais import icms_aliq, uf_without_fcp
from lucro_admin.infra.repositorio_produtos import Produtos

logger = logging.getLogger('lucroadmin.core.taxcalculator')


class TaxCalculator:
    """
    TaxCalculator

        Manually calculates taxes for internal and interstate operations.
        Taxes calculated include ICMS, PIS, COFINS, DIFAL, and FCP
    """

    def __init__(self):
        self.aliq_pis = 1.65 / 100
        self.aliq_cofins = 7.6 / 100

    def tax_calculator(
        self, items, id_bling, sit, uf_dest
    ) -> TaxReturn:
        """
        tax_calculator

        Calculating the taxes of a sale accurately and returning them in an
        organized and formatted way.

        :param self:
        :param items: Order products
        :param id_bling: Unique sale ID, this ID is generated by Bling
        :param status: Order status within Bling
        :param uf_dest: Federal Unit of the sale destination
        :return: Individual return per product as well as totalled for the sale
        :rtype: TaxReturn
        """

        logger.info(
            'Tax Calculator | Starting the tax calculation'
            ' for the order items'
        )

        products = Produtos()

        products_with_tax = []

        # Looping to go through all the items in the sale
        for item in items:
            item_order = OrderItem(
                code=item['codigo'],
                quantity=item['quantidade'],
                value=item['valor'],
            )
            # Setting up the SKU because some come with incorrectly
            # formatted SKUs.
            sku = ConfigSku.configsku(item_order.code)
            icms = icms_tax(
                item_value=item_order.value,
                uf_dest=uf_dest
                )
            difal = difal_tax(
                item_value=item_order.value,
                uf_dest=uf_dest
                )
            pis = pis_tax(
                item_value=item_order.value,
                icms_tax_value=icms,
                difal_tax_value=difal,
                aliq_pis=self.aliq_pis
                )
            cofins = cofins_tax(
                item_value=item_order.value,
                icms_tax_value=icms,
                difal_tax_value=difal,
                aliq_cofins=self.aliq_cofins
                )
            fcp = fcp_tax(
                item_value=item_order.value,
                uf_dest=uf_dest
            )

            total = icms + pis + cofins + difal + fcp

            cost_price = products.consulta_custo(SKU=sku)
            cost_price *= item_order.quantity
            # Formatting the product taxes into a dataclass
            product_tax = ProductWithTax(
                id_bling=id_bling,
                order_status=sit,
                sku=sku,
                quantity=item_order.quantity,
                cost_price=cost_price,
                value=item_order.value,
                icms=icms,
                pis=pis,
                cofins=cofins,
                difal=difal,
                fcp=fcp,
                total=total,
            )
            logger.info(
                'Tax Calculator | Product taxes calculated ->'
                ' %s \nMatthew 22:21',
                product_tax
            )
            products_with_tax.append(product_tax)

        # Adding up all the taxes on the items to total the taxes of the sale.
        taxes_sale = SalesTaxes.sum_taxes(
            products_with_tax, id_bling=id_bling
        )
        logger.info(
                'Tax Calculator | Sale taxes calculated ->'
                ' %s \nMatthew 22:21',
            taxes_sale,
        )
        return TaxReturn(
            product_tax=products_with_tax, sale_tax=taxes_sale
        )


def icms_tax(item_value, uf_dest) -> float:

    if uf_dest == 'SP':
        icms: float = item_value * (18 / 100)

    else:
        aliq_orig: float = 4 / 100
        icms: float = item_value * aliq_orig

    return icms


def difal_tax(item_value, uf_dest):

    if uf_dest != 'SP':
        aliq_dest: float = (icms_aliq(uf_dest) - 4) / 100
        difal: float = item_value * aliq_dest

    else:
        difal: float = 0.0

    return difal


def pis_tax(item_value, icms_tax_value, difal_tax_value, aliq_pis) -> float:

    vbase: float = item_value - icms_tax_value - difal_tax_value

    pis: float = vbase * aliq_pis

    return pis


def cofins_tax(
        item_value,
        icms_tax_value,
        difal_tax_value,
        aliq_cofins
    ) -> float:

    vbase: float = item_value - icms_tax_value - difal_tax_value

    cofins: float = vbase * aliq_cofins

    return cofins


def fcp_tax(item_value, uf_dest) -> float:

    # Validating FCP rates
    without_fcp = uf_without_fcp(uf_dest)
    if not without_fcp and uf_dest != 'SP':
        fcp_tax: float = item_value * (2 / 100)

    else:
        fcp_tax: float = 0.0

    return fcp_tax
